# Generated by Django 5.0.6 on 2024-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
