# Generated by Django 5.0.6 on 2024-06-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0002_friendrequest_friendship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friend_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friendship')),
            ],
        ),
    ]
