# Generated by Django 5.0.6 on 2024-06-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='friend_room',
            new_name='friendship',
        ),
    ]
